# Worksheet- 0
**TO-DO-Task**

Please complete all the problem listed below.

# 4.1 Exercise on Functions:

# Task- 1:

 Create a Python program that converts between different units of measurement.

 • The program should:

 1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).

 2. Ask the user to input the value to be converted.

 3. Perform the conversion and display the result.

 4. Handle potential errors, such as invalid input or unsupported conversion types.

 **• Requirements:**

 1. Functions: Define at least one function to perform the conversion.

 2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).

 3. User Input: Prompt the user to select the conversion type and input the value.

 4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
 return value.

 • Conversion Options:

 1. Length:

 – Convert meters (m) to feet (ft).

 – Convert feet (ft) to meters (m).

 2. Weight:

 – Convert kilograms (kg) to pounds (lbs).

 – Convert pounds (lbs) to kilograms (kg).

 3. Volume:

 – Convert liters (L) to gallons (gal).

 – Convert gallons (gal) to liters (L)

In [ ]:
def convert_units(conversion_type, value):
    conversions = {
        'm_to_ft': value * 3.28084,
        'ft_to_m': value / 3.28084,
        'kg_to_lbs': value * 2.20462,
        'lbs_to_kg': value / 2.20462,
        'l_to_gal': value * 0.264172,
        'gal_to_l': value / 0.264172
    }
    return conversions.get(conversion_type, None)


def main():
    print("Unit Converter:")
    print("1. Length (meters to feet, feet to meters)")
    print("2. Weight (kilograms to pounds, pounds to kilograms)")
    print("3. Volume (liters to gallons, gallons to liters)")

    try:
        choice = int(input("Choose a conversion type (1-3): "))

        if choice == 1:
            print("1. Meters to Feet\n2. Feet to Meters")
            unit_choice = int(input("Select conversion (1-2): "))
            value = float(input("Enter the value to convert: "))
            result = convert_units('m_to_ft' if unit_choice == 1 else 'ft_to_m', value)

        elif choice == 2:
            print("1. Kilograms to Pounds\n2. Pounds to Kilograms")
            unit_choice = int(input("Select conversion (1-2): "))
            value = float(input("Enter the value to convert: "))
            result = convert_units('kg_to_lbs' if unit_choice == 1 else 'lbs_to_kg', value)

        elif choice == 3:
            print("1. Liters to Gallons\n2. Gallons to Liters")
            unit_choice = int(input("Select conversion (1-2): "))
            value = float(input("Enter the value to convert: "))
            result = convert_units('l_to_gal' if unit_choice == 1 else 'gal_to_l', value)

        else:
            print("Invalid choice. Please select a number between 1 and 3.")
            return

        if result is not None:
            print(f"Converted value: {result:.4f}")
        else:
            print("Conversion type not supported.")

    except ValueError:
        print("Invalid input! Please enter a valid number.")

if __name__ == "__main__":
    main()

Unit Converter:
1. Length (meters to feet, feet to meters)
2. Weight (kilograms to pounds, pounds to kilograms)
3. Volume (liters to gallons, gallons to liters)
Choose a conversion type (1-3): 2
1. Kilograms to Pounds
2. Pounds to Kilograms
Select conversion (1-2): 1
Enter the value to convert: 42
Converted value: 92.5940

# Task- 2:
 Create a Python program that performs various mathematical operations on a list of numbers.

 • The Program should:
 1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
 of the numbers).
 2. Ask the user to input a list of numbers (separated by spaces).
 3. Perform the selected operation and display the result.
 4. Handle potential errors, such as invalid input or empty lists.

• Requirements:

 1. Functions: Define at least one function for each operation (sum, average, maximum, mini
mum).
 2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
 empty lists).
 3. User Input: Prompt the user to select the operation and input the list of numbers.
 4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
 return value.

In [ ]:
def calculate_sum(numbers):
    return sum(numbers)

def calculate_average(numbers):
    return sum(numbers) / len(numbers) if numbers else None

def find_maximum(numbers):
    return max(numbers)

def find_minimum(numbers):
    return min(numbers)

def main():
    print("Mathematical Operations on a List:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    try:
        choice = int(input("Choose an operation (1-4): "))

        numbers = list(map(float, input("Enter a list of numbers (separated by spaces): ").split()))

        if not numbers:
            print("Error: The list is empty. Please enter valid numbers.")
            return

        if choice == 1:
            result = calculate_sum(numbers)
        elif choice == 2:
            result = calculate_average(numbers)
        elif choice == 3:
            result = find_maximum(numbers)
        elif choice == 4:
            result = find_minimum(numbers)
        else:
            print("Invalid choice. Please select a number between 1 and 4.")
            return

        print(f"Result: {result:.4f}")

    except ValueError:
        print("Invalid input! Please enter only numbers.")

if __name__ == "__main__":
    main()

Mathematical Operations on a List:
1. Sum
2. Average
3. Maximum
4. Minimum
Choose an operation (1-4): 3
Enter a list of numbers (separated by spaces): 80 31 21 25
Result: 80.0000

# 4.2 Exercise on List Manipulation:
 1. Extract Every Other Element:

 Write a Python function that extracts every other element from a list, starting from the first element.

 • Requirements:

 – Define a function extract
 every
 other(lst) that takes a list lst as input and returns a
 new list containing every other element from the original list.

 – Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5]

In [ ]:
def extract_every_other(lst):
    return lst[::2]

example_list = [1, 2, 3, 4, 5, 6]
result = extract_every_other(example_list)
print(result)

[1, 3, 5]

2. Slice a Sublist:

 Write a Python function that returns a sublist from a given list, starting from a specified index and
 ending at another specified index.

 • Requirements:

 – Define a function get
 sublist(lst, start, end) that takes a list lst, a starting index
 start, and an ending index end as input and returns the sublist from start to end (inclusive).

 – Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
 be [3, 4, 5].

In [ ]:
def get_sublist(lst, start, end):
    return lst[start:end+1]


print(get_sublist([1, 2, 3, 4, 5, 6], 2, 4))

[3, 4, 5]

3. Reverse a List Using Slicing:

 Write a Python function that reverses a list using slicing.
 • Requirements:

 – Define a function reverse
 slicing.
 list(lst) that takes a list lst and returns a reversed list using

 – Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3 , 2, 1].

In [ ]:
def reverse_slicing_list(lst):
    return lst[::-1]

print(reverse_slicing_list([1, 2, 3, 4, 5]))

[5, 4, 3, 2, 1]

 4. Remove the First and Last Elements:

 Write a Python function that removes the first and last elements of a list and returns the resulting
 sublist.

 • Requirements:

 – Define a function remove
 first
 last(lst) that takes a list lst and returns a sublist without
 the first and last elements using slicing.

 – Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4]

In [ ]:
def remove_first_last(lst):
    return lst[1:-1]

print(remove_first_last([1, 2, 3, 4, 5]))

[2, 3, 4]

5. Get the First n Elements:

 Write a Python function that extracts the first n elements from a list.

 • Requirements:

 – Define a function get
 first
 n(lst, n) that takes a list lst and an integer n as input and
 returns the first n elements of the list using slicing.

 – Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [ ]:
def get_first_n(lst, n):

    return lst[:n]

print(get_first_n([1, 2, 3, 4, 5], 3))

[1, 2, 3]

 6. Extract Elements from the End:

 Write a Python function that extracts the last n elements of a list using slicing.

 • Requirements:
 – Define a function get
 last
 n(lst, n) that takes a list lst and an integer n as input and
 returns the last n elements of the list.

 – Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [ ]:
def get_last_n(lst, n):
    return lst[-n:]

print(get_last_n([1, 2, 3, 4, 5], 2))

[4, 5]

 7. Extract Elements in Reverse Order:

 Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
 element and skipping one element in between.

 • Requirements:
 – Define a function reverse
 skip(lst) that takes a list lst and returns a new list containing
 every second element starting from the second-to-last, moving backward.

 – Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [ ]:
def reverse_skip(lst):
    return lst[-2::-2]

print(reverse_skip([1, 2, 3, 4, 5, 6]))

[5, 3, 1]

# 4.3 Exercise on Nested List:
 1. Flatten a Nested List:

 Write a Python function that takes a nested list and flattens it into a single list, where all the elements
 are in a single dimension.

 • Requirements:

 – Define a function flatten(lst) that takes a nested list lst and returns a flattened version
 of the list.

 – Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [ ]:
def flatten(lst):
    flat_list = []
    for sublist in lst:
        for item in sublist:
            flat_list.append(item)
    return flat_list

nested_list = [[1, 2], [3, 4], [5]]
flattened_list = flatten(nested_list)
print(flattened_list)

[1, 2, 3, 4, 5]

 2. Accessing Nested List Elements:

 Write a Python function that extracts a specific element from a nested list given its indices.
 • Requirements:

 – Define a function access
 nested
 element(lst, indices) that takes a nested list lst and
 a list of indices indices, and returns the element at that position.

 – Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
 2], the output should be 6.

In [ ]:
def access_nested_element(lst, indices):

    for index in indices:
        lst = lst[index]
    return lst

lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]
result = access_nested_element(lst, indices)
print(result)

6

 3. Sum of All Elements in a Nested List:

 Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

 • Requirements:

 – Define a function sum
 nested(lst) that takes a nested list lst and returns the sum of all
 the elements.

 – Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [ ]:
def sum_nested(lst):
    total = 0

    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item

    return total

lst = [[1, 2], [3, [4, 5]], 6]
result = sum_nested(lst)
print(result)

21

4. Remove Specific Element from a Nested List:

 Write a Python function that removes all occurrences of a specific element from a nested list.

 • Requirements:

 – Define a function remove
 element(lst, elem) that removes elem from lst and returns the
 modified list.

 – Example: Fortheinput lst = [[1, 2], [3, 2], [4, 5]]and elem = 2,the output should
 be [[1], [3], [4, 5]].

In [ ]:
def remove_element(lst, elem):
    new_lst = []

    for item in lst:
        if isinstance(item, list):

            new_lst.append(remove_element(item, elem))
        else:
            if item != elem:
                new_lst.append(item)

    return new_lst


lst = [[1, 2], [3, 2], [4, 5]]
elem = 2
result = remove_element(lst, elem)
print(result)

[[1], [3], [4, 5]]

 5. Find the Maximum Element in a Nested List:

 Write a Python function that finds the maximum element in a nested list (regardless of depth).

 • Requirements:

 – Define a function find
 element.
 max(lst) that takes a nested list lst and returns the maximum

 – Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6

In [ ]:
def find_max(lst):
    max_val = float('-inf')

    for item in lst:
        if isinstance(item, list):
            max_val = max(max_val, find_max(item))
        else:
            max_val = max(max_val, item)

    return max_val

lst = [[1, 2], [3, [4, 5]], 6]
result = find_max(lst)
print(result)

6

 6. Count Occurrences of an Element in a Nested List:
 Write a Python function that counts how many times a specific element appears in a nested list.
 • Requirements:– Define a function count
 occurrences(lst, elem) that counts the occurrences of elem in
 the nested list lst.– Example: Fortheinput lst = [[1, 2], [2, 3], [2, 4]]andelem = 2,theoutputshould
 be 3.

In [ ]:
def count_occurrences(lst, elem):
    count = 0

    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        else:
            if item == elem:
                count += 1

    return count

lst = [[1, 2], [2, 3], [2, 4]]
elem = 2
result = count_occurrences(lst, elem)
print(result)

3

 7. Flatten a List of Lists of Lists:
 Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.
 • Requirements:– Define a function deep
 flatten(lst) that takes a deeply nested list lst and returns a single
 f
 lattened list.– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
 [1, 2, 3, 4, 5, 6, 7, 8].

In [ ]:
def deep_flatten(lst):
    flat_list = []

    for item in lst:
        if isinstance(item, list):
            flat_list.extend(deep_flatten(item))
        else:
            flat_list.append(item)

    return flat_list


nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
result = deep_flatten(nested_list)
print(result)

[1, 2, 3, 4, 5, 6, 7, 8]

8. Nested List Average:
 Write a Python function that calculates the average of all elements in a nested list.
 • Requirements:– Define a function average
 of all the elements.
 nested(lst) that takes a nested list lst and returns the average– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [ ]:
def average_nested(lst):

    flat_list = []
    for sublist in lst:
        for item in sublist:
            flat_list.append(item)


    total_sum = sum(flat_list)
    total_elements = len(flat_list)


    if total_elements == 0:
        return 0
    return total_sum / total_elements


nested_list = [[1, 2], [3, 4], [5, 6]]
result = average_nested(nested_list)
print(result)

3.5

# To- Do- NumPy
 Please complete all the problems listed below

# 10.1 Basic Vector and Matrix Operation with Numpy.
 Problem- 1: Array Creation:
 Complete the following Tasks:
 1. Initialize an empty array with size 2X2.

In [ ]:
import numpy as np

empty_array = np.empty((2, 2))
print("Empty Array:\n", empty_array)

Empty Array:
 [[1.3649124e-316 0.0000000e+000]
 [9.0411522e+271 1.0212402e+277]]

2. Initialize an all one array with size 4X2.

In [ ]:
ones_array = np.ones((4, 2))
print("\nOnes Array:\n", ones_array)

Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

 3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [ ]:
filled_array = np.full((3, 3), 7)
print("\nFilled Array (7):\n", filled_array)

Filled Array (7):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [ ]:
existing_array = np.array([[1, 2, 3], [4, 5, 6]])

zeros_like_array = np.zeros_like(existing_array)
print("\nZeros Like Array:\n", zeros_like_array)

Zeros Like Array:
 [[0 0 0]
 [0 0 0]]

 5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [ ]:
ones_like_array = np.ones_like(existing_array)
print("\nOnes Like Array:\n", ones_like_array)

Ones Like Array:
 [[1 1 1]
 [1 1 1]]

 6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
new_list = [1, 2, 3, 4]

numpy_array = np.array(new_list)
print("\nNumPy Array from List:\n", numpy_array)

NumPy Array from List:
 [1 2 3 4]

# Problem- 2: Array Manipulation: Numerical Ranges and Array indexing:
 Complete the following tasks:
 1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [ ]:
import numpy as np

array_10_to_49 = np.arange(10, 50)
print("Array from 10 to 49:", array_10_to_49)

Array from 10 to 49: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

 2. Create a 3X3 matrix with values ranging from 0 to 8.
 {Hint:look for np.reshape()}

In [ ]:
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n3x3 Matrix from 0 to 8:\n", matrix_3x3)

3x3 Matrix from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [ ]:
identity_matrix = np.eye(3)
print("\n3x3 Identity Matrix:\n", identity_matrix)

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Create a random array of size 30 and find the mean of the array.
 {Hint:check for np.random.random() and array.mean() function}

In [ ]:
random_array = np.random.random(30)

mean_value = random_array.mean()
print("\nMean of Random Array:", mean_value)

Mean of Random Array: 0.4895855413361209

5. Create a 10X10 array with random values and find the minimum and maximum values.

In [ ]:
random_10x10 = np.random.random((10, 10))

min_value = random_10x10.min()
max_value = random_10x10.max()
print("\nMinimum value:", min_value)
print("Maximum value:", max_value)

Minimum value: 0.015531419576805483
Maximum value: 0.9874844403307331

 6. Create a zero array of size 10 and replace 5th element with 1.

In [ ]:
zero_array = np.zeros(10)

zero_array[4] = 1
print("\nZero Array with 5th element replaced:", zero_array)

Zero Array with 5th element replaced: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

7. Reverse an array arr = [1,2,0,0,4,0].

In [ ]:
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\nReversed Array:", reversed_arr)

Reversed Array: [0 4 0 0 2 1]

8. Create a 2d array with 1 on border and 0 inside.

In [ ]:
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n2D Array with 1 on Border and 0 Inside:\n", border_array)

2D Array with 1 on Border and 0 Inside:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

 9. Create a 8X8 matrix and fill it with a checkerboard pattern

In [ ]:
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n8x8 Checkerboard Pattern:\n", checkerboard)

8x8 Checkerboard Pattern:
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]

# Problem- 3: Array Operations:
 For the following arrays:
 x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
 v = np.array([9,10]) and w = np.array([11,12]);
 Complete all the task using numpy:
 1. Add the two array.

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

In [ ]:
add_result = np.add(x, y)
print("x + y:\n", add_result)

x + y:
 [[ 6  8]
 [10 13]]

 2. Subtract the two array.

In [ ]:
subtract_result = np.subtract(x, y)
print("\nx - y:\n", subtract_result)

x - y:
 [[-4 -4]
 [-4 -3]]

 3. Multiply the array with any integers of your choice.

In [ ]:
multiply_result = np.multiply(x, 2)
print("\nMultiply x by 2:\n", multiply_result)

Multiply x by 2:
 [[ 2  4]
 [ 6 10]]

 4. Find the square of each element of the array.

In [ ]:
square_result = np.square(x)
print("\nSquare of each element in x:\n", square_result)

Square of each element in x:
 [[ 1  4]
 [ 9 25]]

 5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [ ]:
dot_vw = np.dot(v, w)
print("\nDot product of v and w:", dot_vw)

dot_xv = np.dot(x, v)
print("\nDot product of x and v:\n", dot_xv)

dot_xy = np.dot(x, y)
print("\nDot product of x and y:\n", dot_xy)

Dot product of v and w: 219

Dot product of x and v:
 [29 77]

Dot product of x and y:
 [[19 22]
 [50 58]]

 6. Concatenate x(and)y along row and Concatenate v(and)w along column.
 {Hint:try np.concatenate() or np.vstack() functions.

In [ ]:
concat_xy_rows = np.concatenate((x, y), axis=0)
print("\nConcatenate x and y along rows:\n", concat_xy_rows)

concat_vw_columns = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)
print("\nConcatenate v and w along columns:\n", concat_vw_columns)

Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate v and w along columns:
 [[ 9 11]
 [10 12]]

7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:

try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("\nConcatenate x and v:\n", concat_xv)
except Exception as e:
    print("\nError when concatenating x and v:", e)

v_reshaped = v.reshape(2, 1)
concat_xv_reshaped = np.concatenate((x, v_reshaped), axis=1)
print("\nConcatenate reshaped x and v:\n", concat_xv_reshaped)

Error when concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Concatenate reshaped x and v:
 [[ 1  2  9]
 [ 3  5 10]]

# Problem- 4: Matrix Operations:
 • For the following arrays:
 A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
 Prove following with Numpy:
 1. Prove A.A−1 = I.

In [ ]:
import numpy as np

A = np.array([[3, 4], [7, 8]])
A_inv = np.linalg.inv(A)

product = np.dot(A, A_inv)
print("A * A_inv:\n", product)

A * A_inv:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

2. Prove AB= BA.

In [ ]:
B = np.array([[5, 3], [2, 1]])

AB = np.dot(A, B)
BA = np.dot(B, A)

print("AB:\n", AB)
print("\nBA:\n", BA)

AB:
 [[23 13]
 [51 29]]

BA:
 [[36 44]
 [13 16]]

3. Prove (AB)T = BTAT.

In [ ]:
AB_T = np.transpose(np.dot(A, B))
BT_AT = np.dot(np.transpose(B), np.transpose(A))


print("Transpose of AB:\n", AB_T)
print("\nB^T * A^T:\n", BT_AT)

Transpose of AB:
 [[23 51]
 [13 29]]

B^T * A^T:
 [[23 51]
 [13 29]]

• Solve the following system of Linear equation using Inverse Methods.
 2x −3y+z =−1

 x −y+2z =−3

 3x +y−z =9

 {Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

In [ ]:
import numpy as np

A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])

X = np.dot(np.linalg.inv(A), B)
print("Solution (x, y, z):", X)

Solution (x, y, z): [ 2.  1. -2.]

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func
tion of Numpy}

In [ ]:
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

A_inv = np.linalg.inv(A)
product = np.dot(A, A_inv)
print("A * A_inv:\n", product)

AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nAB:\n", AB)
print("\nBA:\n", BA)

AB_T = np.transpose(np.dot(A, B))
BT_AT = np.dot(np.transpose(B), np.transpose(A))
print("\nTranspose of AB:\n", AB_T)
print("\nB^T * A^T:\n", BT_AT)

A_eq = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_eq = np.array([-1, -3, 9])

X = np.dot(np.linalg.inv(A_eq), B_eq)
print("\nSolution (x, y, z):", X)

A * A_inv:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB:
 [[23 13]
 [51 29]]

BA:
 [[36 44]
 [13 16]]

Transpose of AB:
 [[23 51]
 [13 29]]

B^T * A^T:
 [[23 51]
 [13 29]]

Solution (x, y, z): [ 2.  1. -2.]

# 10.2 Experiment: How Fast is Numpy?
 In this exercise, you will compare the performance and implementation of operations using plain Python
 lists (arrays) and NumPy arrays. Follow the instructions:
 1. Element-wise Addition:

 • Using Python Lists, perform element-wise addition of two lists of size 1,000,000. Measure
 and Print the time taken for this operation.

In [ ]:
import time

size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))

start_time = time.time()
result = [list1[i] + list2[i] for i in range(size)]
end_time = time.time()

print("Time taken using Python lists:", end_time - start_time, "seconds")

Time taken using Python lists: 0.22888851165771484 seconds

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
 this operation.

In [ ]:
import numpy as np
import time

size = 1_000_000
array1 = np.arange(size)
array2 = np.arange(size)

start_time = time.time()
result = array1 + array2
end_time = time.time()

print("Time taken using NumPy arrays:", end_time - start_time, "seconds")

Time taken using NumPy arrays: 0.005263090133666992 seconds

2. Element-wise Multiplication

 • Using Python Lists, perform element-wise multiplication of two lists of size 1,000,000.
 Measure and Print the time taken for this operation.

In [ ]:
import time

size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))

start_time = time.time()
result = [list1[i] * list2[i] for i in range(size)]
end_time = time.time()

print("Time taken using Python lists:", end_time - start_time, "seconds")

Time taken using Python lists: 0.08025670051574707 seconds

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
 this operation.

In [ ]:
import numpy as np
import time

size = 1_000_000
array1 = np.arange(size)
array2 = np.arange(size)

start_time = time.time()
result = array1 * array2
end_time = time.time()

print("Time taken using NumPy arrays:", end_time - start_time, "seconds")

Time taken using NumPy arrays: 0.002788066864013672 seconds

3. Dot Product

 • Using Python Lists, compute the dot product of two lists of size 1,000,000. Measure and
 Print the time taken for this operation.

In [ ]:
import time

size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))

start_time = time.time()
dot_product = sum(list1[i] * list2[i] for i in range(size))
end_time = time.time()

print("Time taken using Python lists:", end_time - start_time, "seconds")

Time taken using Python lists: 0.09548044204711914 seconds

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
 this operation.

In [ ]:
import numpy as np
import time

size = 1_000_000
array1 = np.arange(size)
array2 = np.arange(size)

start_time = time.time()
dot_product = np.dot(array1, array2)
end_time = time.time()

print("Time taken using NumPy arrays:", end_time - start_time, "seconds")

Time taken using NumPy arrays: 0.0017752647399902344 seconds

4. Matrix Multiplication

 • Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Mea
sure and print the time taken for this operation.

In [ ]:
import time

size = 1000
matrix1 = [[i for i in range(size)] for _ in range(size)]
matrix2 = [[i for i in range(size)] for _ in range(size)]
result = [[0] * size for _ in range(size)]

start_time = time.time()
for i in range(size):
    for j in range(size):
        result[i][j] = sum(matrix1[i][k] * matrix2[k][j] for k in range(size))
end_time = time.time()

print("Time taken using Python lists:", end_time - start_time, "seconds")

Time taken using Python lists: 180.89332485198975 seconds

 • Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
 Measure and print the time taken for this operation

In [ ]:
import numpy as np
import time

size = 1000
matrix1 = np.arange(size * size).reshape(size, size)
matrix2 = np.arange(size * size).reshape(size, size)

start_time = time.time()
result = np.dot(matrix1, matrix2)
end_time = time.time()

print("Time taken using NumPy arrays:", end_time - start_time, "seconds")

Time taken using NumPy arrays: 3.624842405319214 seconds